name: Dev Workflow

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          ref: dev

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"

      - name: Installing dependencies
        run: yarn install --frozen-lockfile

      - name: Build for production
        run: yarn build

      - name: Compress file
        run: cd build && zip ../EDN_Auto_V2.zip * && cd ..

  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          path: EDN_Auto_V2.zip
