name: PreRelease Branch Workflow

on:
  push:
    tags:
      - pre-v*

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Installing dependencies
        run: bun install

      - name: Build for production
        run: bun run build

      - name: Build release branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          disable_nojekyll: true
          publish_branch: pre-release
          publish_dir: ./build

      - name: Build release branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          disable_nojekyll: true
          publish_branch: nightly
          publish_dir: ./build
