name: PreRelease Workflow

on:
  push:
    tags:
      - pre-v*

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"

      - name: Installing dependencies
        run: yarn install --frozen-lockfile

      - name: Build for production
        run: yarn build

      - name: Rename build folder
        run: mv build EDN_Auto_V2

      - name: Compress build
        run: zip -r EDN_Auto_V2.zip EDN_Auto_V2

      - name: Generate MD5 Checksum
        run: md5sum EDN_Auto_V2.zip > checksum.md5

      # - name: Upload zip file
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: EDN_Auto_V2.zip
      #     path: EDN_Auto_V2.zip

      # - name: Upload checksum file
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: EDN_Auto_V2.zip
      #     path: checksum.md5

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: "Pre-release ${{ github.ref_name }}"
          body_path: "PRE-RELEASE.md"
          files: |
            EDN_Auto_V2.zip
            checksum.md5
          prerelease: true
