on:
  push:
    # Sequence of patterns matched against refs/tags
    branches:
      - "*"
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"
      - run: yarn
      - run: yarn build

      - uses: actions/checkout@master
      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.1
        with:
          directory: "build"
          type: "zip"
          filename: "EDN Auto V2.zip"
          exclusions: "*.git* /*node_modules/* .editorconfig"
      - name: Upload Release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "EDN Auto V2.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
