name: Release Workflow

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"

      - name: Installing dependencies
        run: yarn install --frozen-lockfile

      - name: Build for production
        run: yarn build

      - name: Rename build folder
        run: mv build EDN_Auto_V3

      - name: Compress build
        run: zip -r EDN_Auto_V3.zip EDN_Auto_V3

      - name: Generate MD5 Checksum
        run: md5sum EDN_Auto_V3.zip > checksum.md5

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "EDN_Auto_V3.zip,checksum.md5"
          bodyFile: "RELEASE.md"
