name: Release Branch Workflow

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"

      - name: Installing dependencies
        run: yarn install --frozen-lockfile

      - name: Build for production
        run: yarn build

      - name: Build release branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          disable_nojekyll: true
          publish_branch: production
          publish_dir: ./build

      - name: Build release branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          disable_nojekyll: true
          publish_branch: stable
          publish_dir: ./build
